POST http://localhost:8080/user/register
Content-Type: application/json

{
  "fullname": "raveen",
  "username": "raveenkaarri",
  "password": "rav123"
}

###
POST http://localhost:8080/user/login
Content-Type: application/json

{
  "username": "raveenkaarri",
  "password": "rav123"
}


###
GET http://localhost:8080/user/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJmdWxsbmFtZSI6InJhdmVlbiIsInVzZXJuYW1lIjoicmF2ZWVua2FhcnJpIiwicGFzc3dvcmQiOiIkMmIkMTAkdVJjM0dYWFpYMGxabXBJODZwRGtWLjJiZTZIZnRDcmZhREUuL2tGQnZHOGVRTHV2Q29NejIifSwiaWF0IjoxNzYyMDEyNzI0LCJleHAiOjE3NjQ2MDQ3MjR9.-Xb8d0eK5Sgl3nkeK2KoP9n7PLHD8PP66-y-Ibc7eho

### Create a new task
POST http://localhost:8080/tasks
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJmdWxsbmFtZSI6InJhdmVlbiIsInVzZXJuYW1lIjoicmF2ZWVua2FhcnJpIiwicGFzc3dvcmQiOiIkMmIkMTAkdVJjM0dYWFpYMGxabXBJODZwRGtWLjJiZTZIZnRDcmZhREUuL2tGQnZHOGVRTHV2Q29NejIifSwiaWF0IjoxNzYyMDEyNzI0LCJleHAiOjE3NjQ2MDQ3MjR9.-Xb8d0eK5Sgl3nkeK2KoP9n7PLHD8PP66-y-Ibc7eho


{
  "title": "Finish React Project",
  "description": "Complete the task tracker frontend and connect to backend API",
  "priority": "High",
  "due_date": "2025-11-05",
  "status": "Open"
}

###
GET http://localhost:8080/tasks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJmdWxsbmFtZSI6InJhdmVlbiIsInVzZXJuYW1lIjoicmF2ZWVua2FhcnJpIiwicGFzc3dvcmQiOiIkMmIkMTAkdVJjM0dYWFpYMGxabXBJODZwRGtWLjJiZTZIZnRDcmZhREUuL2tGQnZHOGVRTHV2Q29NejIifSwiaWF0IjoxNzYyMDEyNzI0LCJleHAiOjE3NjQ2MDQ3MjR9.-Xb8d0eK5Sgl3nkeK2KoP9n7PLHD8PP66-y-Ibc7eho

###
PATCH http://localhost:8080/tasks/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJmdWxsbmFtZSI6InJhdmVlbiIsInVzZXJuYW1lIjoicmF2ZWVua2FhcnJpIiwicGFzc3dvcmQiOiIkMmIkMTAkdVJjM0dYWFpYMGxabXBJODZwRGtWLjJiZTZIZnRDcmZhREUuL2tGQnZHOGVRTHV2Q29NejIifSwiaWF0IjoxNzYyMDEyNzI0LCJleHAiOjE3NjQ2MDQ3MjR9.-Xb8d0eK5Sgl3nkeK2KoP9n7PLHD8PP66-y-Ibc7eho

{
  "priority": "Low",
  "status": "Done"
}